name: Create Release Archives

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release Archives
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: |
          zip -r /tmp/BloxDrive-${{ github.ref_name }}.zip . -x "*.git*" ".github*"
          
      - name: Create Tar Archive
        run: |
          tar -czvf /tmp/BloxDrive-${{ github.ref_name }}.tar.gz --exclude=.git --exclude=.github .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/BloxDrive-${{ github.ref_name }}.zip
            /tmp/BloxDrive-${{ github.ref_name }}.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
